# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'children2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_childrenForm2(object):
    def setupUi(self, childrenForm2):
        childrenForm2.setObjectName("childrenForm2")
        childrenForm2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(childrenForm2)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(50, 50, 541, 401))
        self.textEdit.setObjectName("textEdit")
        childrenForm2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(childrenForm2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        childrenForm2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(childrenForm2)
        self.statusbar.setObjectName("statusbar")
        childrenForm2.setStatusBar(self.statusbar)

        self.retranslateUi(childrenForm2)
        QtCore.QMetaObject.connectSlotsByName(childrenForm2)

    def retranslateUi(self, childrenForm2):
        _translate = QtCore.QCoreApplication.translate
        childrenForm2.setWindowTitle(_translate("childrenForm2", "MainWindow"))
        self.textEdit.setHtml(_translate("childrenForm2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">我是子窗口</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    childrenForm2 = QtWidgets.QMainWindow()
    ui = Ui_childrenForm2()
    ui.setupUi(childrenForm2)
    childrenForm2.show()
    sys.exit(app.exec_())
